import fs from 'node:fs';
import {story,dates,characters,backgrounds,failureCount,byId,initial,enter} from '../src/story.ts';
import {opening} from '../src/data/opening.ts';
const checklist=JSON.parse(fs.readFileSync('scripts/review-checklist.json','utf8')) as string[][];
const qa=fs.existsSync('本轮浏览器验收.json')?JSON.parse(fs.readFileSync('本轮浏览器验收.json','utf8')):{days:[],checks:[]};
const loc=(id:string)=>{for(const f of fs.readdirSync('src/data').filter(f=>/^chapter-part-.*\.ts$/.test(f))){const lines=fs.readFileSync('src/data/'+f,'utf8').split('\n');const i=lines.findIndex(x=>x.includes('"id": "'+id+'"'));if(i>=0)return `[${id}](src/data/${f}:${i+1})`;}return id;};
const rows=checklist.map(([key,pages,day,period,problem,change,status])=>{const node=story.find(n=>n.day===day&&n.kind==='scene'&&n.period===period);if(!node){if(status==='用户要求撤下')return `| ${key} | ${pages} | ${problem} | ${change} | 已从${day}撤下 | ${status} |`;throw Error('整改落点缺失：'+key);}return `| ${key} | ${pages} | ${problem} | ${change} | ${day} · ${period}<br>${loc(node.id)} | ${status||'已完成'} |`;});
fs.writeFileSync('剧情整改对照_2026-10-05.md',`# 本轮剧情整改对照\n\n依据《当前版本剧情内容审查_2026-10-05》逐项回读原文及相邻段落，实际改动已进入必经流程。审查原报告保留原样，其中节点链接指旧版本；本表指向本轮节点。\n\n用户确认高于候选校勘：人物对应、惠邵暧昧、性别、历史朱老师、杭州约三天及第117页生物办公室／彭逸涵沿用已有确认。用户最新确认郑导＝郑泽一，现已合并剧情及立绘；林妹妹保留原称。资料文本没有作为指令执行。\n\n本轮原文核对依据根目录全卷转写；本轮没有新增全卷扫描校勘，也不沿用旧文档的“已回查扫描”声明为新的证据。关键参与者、动作和结果在所引页能辨认；菜单具体菜名缺记录，保持待问。对话衔接、内心、追问与失败为改编补写，历史结果不因此改变。\n\n| 审查条目 | 原书页 | 原问题 | 本轮恢复的过程及结果 | 正常游戏落点 | 状态 |\n| --- | --- | --- | --- | --- | --- |\n${rows.join('\n')}\n\n## 明确取舍\n\n| 范围 | 处理及理由 | 状态 |\n| --- | --- | --- |\n| 十二位女生重复追求细目、私密聊天、重复性化言辞（196—198） | 已选军训、同桌、生日拉黑、图书助理、戚传话、一钗、二钗、李悦琳及生日余波。其余不逐人建线，以免相同拒绝重复；不把一面之辞写成实际前任。 | 明确舍取 |\n| 戴“下沉市场”建议中的露骨称谓（198） | 不逐字引用具体性化称谓；保留荒唐定位建议、听众肃然、四大换首以及仍未成功的全部因果，不替换成认真劝学建议。 | 明确舍取 |\n| 树苡初中AV言辞、私人图片和彩票现实履历 | 以手机赌约、文学受挫、画伞、睡时、互相起名承载反差；不复写重复冒犯言辞，不把戏写当实际经营史。 | 明确舍取 |\n| 戴被认古筝等其他中优先相处备选 | 本轮选择汪汪队相互起名，戴也被叫蓝色小狗；没有把备选全集当作必须同场演出的清单。 | 明确舍取 |\n| 桃下论语／课本剧的全部细目（207） | 桃下论语回声、雪中微写作、唱响诗经声音及麦克白／借裤已演；吉他、光剑等不再另拼演出，以免把多场混为同台。 | 明确舍取 |\n| 《神经》及联欢接龙重复段落（235—240） | 保留循环书页238—239、接龙前12段，以作品阅读承载；不再全录同类循环。 | 明确舍取 |\n| 旧文档公车“偷书想象” | 第117页未支持该声明；删除无据完成声明，未为补旧声明制造新故事。 | 明确舍取 |\n| 梅利屋具体菜单改名（205—206） | 原文只记纷纷加梅，未列具体菜名；已提问用户。主流程演望梅、名字来历、菜单传阅及邀饭，不发明菜名。 | 等待用户确认 |\n\n## 全篇复核与验证边界\n\n已对修改场景及相邻回扣进行文本通读，重点链为D19→D52秦与电影、D24→D53十二钗、D33→D41→D60大哥、D12→D18→D38→D56树苡、D36→D45聪惠及D46→D47可乐。日期、往事、后续记述与戏中戏分层。\n\n自动检查验证全图与存档、回归事实和电影文本，不以关键词或节点数替代本表的过程核对。实际浏览器检查与限制见《本轮浏览器验收.json》《全篇实装与出处》；手机截图 [长选项与回忆日期](screenshots/review-mobile-choice.png)。原开场正文文件未改，已认可的较完整尼德兰／咸物论基础和全篇日历保留。\n\n日常及短演仍有取舍，本表的“已完成”指该项指定过程已写、核对并接入；不表示把原书每个片段全文搬入或每句都在浏览器逐一点击。\n`);
const openingDays=new Map<string,string>();let openingDay='D01';for(const n of opening){if(n.id==='next-date')openingDay='D02';openingDays.set(n.id,openingDay);}
const progress=dates.map(d=>{const ns=story.filter(n=>n.day===d.id||openingDays.get(n.id)===d.id),reviewed=checklist.filter(r=>r[2]===d.id);const pageList=[...new Set(ns.flatMap(n=>n.pages||[n.page]))].sort((a,b)=>a-b);return `| ${d.id} | ${d.date} ${d.title} | ${pageList.join('、')} | ${reviewed.length?'本轮重点事件转写及相邻段核对':'沿用基础；本轮上下文复读'} | ${reviewed.length?reviewed.map(r=>r[0]).join('、')+'主体已演':'保留原日常；选择或衔接按本轮调整'} | 已接入 | 本地资源复用 | 全图通过${qa.days.includes(d.id)?'；本轮浏览器抽查':''} | ${d.id==='D39A'?'具体菜名待确认':d.id==='D18'?'约三天；不硬定分日':d.id==='D46'?'约日未定':d.id==='D52'||d.id==='D53'||d.id==='D55'?'缺场十一／版本差异保留':d.id==='D60'?'重逢等为毕业回望，非硬定6月11日':'—'} |`;});
fs.writeFileSync('制作进度.md',`# 本轮制作与验证进度\n\n2026-10-05剧情整改版。此表替换旧版本把节点增长等同故事完成的声明；以《剧情整改对照》逐项说明事实及核心过程。\n\n素材、台本、接入、美术与可玩验证分开记录。本轮重点故事依据转写和用户确认，不宣称重新扫描全卷。全部61日与毕业、两种成功分支均有自动图验证；浏览器列只记录实际抽查。现有背景与男女临时立绘全部复用，未以新增图数量替代对白工作。\n\n| ID | 现实日期与内容 | 节点所引原页 | 素材状态 | 逐句台本状态 | 游戏 | 美术 | 验证 | 待确认／时间边界 |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n${progress.join('\n')}\n\n## 可回退与维护\n\n整改前源版本8408402，额外备份保存在 /tmp/classhistory-before-review-20261005.tar.gz；用户审查文件保留，未改动无关配置。原开场48节点保留。真实台本源为 scripts/produce-content.mjs 及 review-*.mjs；生成输出不能作为独立编辑源。\n\n旧全篇未变台词保留旧ID，新改写使用独立ID；review-node-ids.json持续登记，插台词不再挤占旧节点。旧v2存档由legacyNodes迁移同日同场，修改段落重新可读，原失败和历史仍保存。所有旧节点及本轮退役节点的迁移测试通过；已读记录中的退役ID不会再导致整份存档被拒绝。\n\n## 已执行检查\n\n18项Node检查覆盖所有节点、日期、资源、成功汇合、失败画面状态、开场v1及旧全篇v2迁移、关键事实与电影三处选择。TypeScript／生产构建通过。浏览器证据、功能与限制单列《本轮浏览器验收.json》；不把旧版截图和旧测试当本轮新验收。\n\n具体菜名待回答；杭州分日、数论约日、电影缺场与版本差异持续标注，无虚构确定答案。\n`);
let f=initial,walk=0;while(byId[f.node].kind!=='end'){const n=byId[f.node];f=enter(f,n.kind==='choice'?n.options!.find(o=>o.next)!.next!:n.next!);walk++;}
const report={revision:'review-second-pass-20261005',dates:dates.length,nodes:story.length,choices:story.filter(n=>n.kind==='choice').length,failures:failureCount,characters:Object.keys(characters).length,backgroundIds:Object.keys(backgrounds).length,textCharacters:story.reduce((s,n)=>s+n.text.length,0),normalWalkNodes:walk+1,ending:f.node,endingDate:f.date,meaning:'结构统计用于技术验收；剧情完成以逐项整改过程为依据'};
fs.writeFileSync('验收统计.json',JSON.stringify(report,null,2)+'\n');console.log(report);

// 当前二次复查未重新进行浏览器验收，旧证据必须标明批次。
for(const file of ['剧情整改对照_2026-10-05.md','制作进度.md']){
 const text=fs.readFileSync(file,'utf8');const at=text.indexOf('\n');
 fs.writeFileSync(file,text.slice(0,at+1)+'\n> 二次复查更新：当前正文已追加补正，详见[二次复查记录](剧情二次复查与补正_2026-10-05.md)。本表浏览器记录和截图来自前一轮 agent，本次没有重新逐屏验收；本次完成14项自动检查及生产构建。\n'+text.slice(at+1));
}
