export const backgrounds:Record<string,string> = {
  "classroom": "高中楼 · 七班教室",
  "corridor": "教学楼走廊",
  "sunset": "教室 · 夕照",
  "rear": "七班 · 后排",
  "snow-track": "学校操场 · 雪地",
  "track": "学校操场",
  "cafeteria": "食堂",
  "biology": "生物办公室",
  "math-office": "数学办公室",
  "history-office": "历史办公室",
  "dorm": "学生宿舍",
  "home": "居家书桌",
  "bus": "旅行大巴",
  "great-wall": "八达岭古长城",
  "noodle": "面店",
  "hall": "逸夫楼报告厅",
  "gate": "校门",
  "hotpot": "火锅店",
  "park": "公园步道",
  "infirmary": "医务室／医院布景",
  "netherlands": "尼德兰街景",
  "cafe": "咖啡馆",
  "train": "高铁车厢",
  "west-lake": "杭州 · 西湖",
  "songcheng": "杭州 · 宋城",
  "workshop": "茶艺与画伞活动室",
  "hotel": "杭州 · 旅馆",
  "mayor-office": "镜中花 · 镇长办公室",
  "company": "镜中花 · 钢材公司",
  "archive": "镜中花 · 档案室",
  "film-home": "镜中花 · 嘉然家",
  "flood": "镜中花 · 洪灾回忆",
  "railway": "镜中花 · 铁路远景",
  "barbecue": "烤肉店",
  "film-street": "镜中花 · 花城街道",
  "liangzhu": "杭州 · 良渚博物院",
  "yue-temple": "杭州 · 岳王庙",
  "xixi": "杭州 · 西溪湿地",
  "library": "学校图书馆",
  "listening-lab": "英语听口机房",
  "washroom": "卫生间洗手区及入口",
  "elevator-lobby": "教学楼电梯口",
  "group-restaurant": "旅行团餐厅",
  "teacher-office": "教师办公室与沙发长椅",
  "company-basement": "公司地下室及拐角",
  "company-gate": "建材公司大门外",
  "classroom-night": "夜间教室",
  "classroom-snow": "雪天教室",
  "classroom-exam": "考场教室",
  "classroom-window": "教室窗边视角",
  "sports-dome": "气膜馆内部",
  "backstage": "舞台后台与换装区",
  "songcheng-stage": "宋城演出舞台",
  "songcheng-rings": "宋城水上铁环设施",
  "cafeteria-entrance": "食堂门外",
  "graduation-photo": "毕业合影场地",
  "chronicle-desk": "书桌上的班史"
};
export const backgroundDescriptions:Record<string,string> = {
  "classroom": "七班日常上课的教室。木课桌、青绿色座椅与窗边的光影，陪伴了一年的课堂与课间。",
  "corridor": "教室外的教学楼走廊。窗光落在地面，串起进出课堂和课间相遇。",
  "sunset": "夕阳落进熟悉的七班教室，桌椅与黑板染上傍晚的暖色。",
  "rear": "七班教室后排，书柜、书本与课间杂物留下日常生活的痕迹。",
  "snow-track": "雪后的学校操场，积雪与脚印记下冬季的课间。",
  "track": "学校的室外操场，跑道与运动场承载体育课和课间活动。",
  "cafeteria": "学校食堂，日常用餐和餐桌边的闲谈发生在这里。",
  "biology": "生物老师的办公室，课本、资料与答疑的桌面构成另一间小课堂。",
  "math-office": "数学办公室，同学们带着卷子和疑问来这里继续讨论。",
  "history-office": "历史办公室，书籍与办公桌之间留下答疑和老师的关照。",
  "dorm": "学生宿舍，课堂之外的谈话、录音与日常在这里延续。",
  "home": "家中的书桌与生活空间，用于居家学习及相关回忆。",
  "bus": "旅行大巴的车厢，一路的风景与同学间的交谈从这里展开。",
  "great-wall": "八达岭古长城，城墙随着山势延伸，留下共同出游的记忆。",
  "noodle": "一间普通面店，热气与桌椅组成校外用餐的小天地。",
  "hall": "逸夫楼报告厅，用于集体活动、舞台演出和校园聚会。",
  "gate": "校园入口，记录来校、离校以及考试前后的等候。",
  "hotpot": "火锅店的聚餐桌，腾起的热气让课堂之外的交谈慢下来。",
  "park": "公园里的树荫与步道，用于散步、交谈及重逢的场景。",
  "infirmary": "带病床和隔帘的医务室，也作为学生电影中的医院布景。",
  "netherlands": "尼德兰的街道风景，出现在远行与异地生活的相关叙述中。",
  "cafe": "咖啡馆里的桌椅与窗光，也承载《镜中花》角色之间的谈话。",
  "train": "高铁车厢，窗外风景伴着游学旅途不断向后移动。",
  "west-lake": "杭州西湖，湖水与岸边树影构成游学照片里的风景。",
  "songcheng": "杭州宋城的景区街巷，传统建筑与游览路线交织。",
  "workshop": "茶艺与画伞活动室，桌面为体验活动和手工作品留出空间。",
  "hotel": "杭州游学期间的旅馆房间，休息与同学间的闲谈在此展开。",
  "mayor-office": "《镜中花》中的镇长办公室，桌上的文件与账目连接案件线索。",
  "company": "《镜中花》中的钢材公司办公室，经理的桌椅与窗外厂区构成谈话背景。",
  "archive": "《镜中花》中的档案室，成排卷宗与账簿保存着调查所需的记录。",
  "film-home": "《镜中花》中的嘉然家，亲人间的谈话回到安静的生活空间。",
  "flood": "《镜中花》中的洪灾回忆画面，呈现角色所谈及的受灾家乡。",
  "railway": "《镜中花》中的铁路远景，延伸的铁轨与远方列车连接故事的开端。",
  "barbecue": "烤肉店里的聚餐空间，餐桌与烤炉承载校外的闲聊。",
  "film-street": "《镜中花》中的花城街道，用于角色相遇和行走的室外场景。",
  "liangzhu": "杭州良渚博物院，展厅与文物陈列构成游学参观的背景。",
  "yue-temple": "杭州岳王庙，庭院与建筑留下游学参观的片段。",
  "xixi": "杭州西溪湿地，水道与绿树展开另一段游学风景。",
  "library": "学校图书馆，书架与阅读桌为课间阅读留出安静空间。",
  "listening-lab": "听口机房里整齐排着电脑与耳麦。隔板分开座位，每个人都要听清属于自己的那一段声音。",
  "washroom": "教学楼卫生间的洗手区，两侧水池相对，后方连着隔间。课间的声音与冷热水的反差都留在这里。",
  "elevator-lobby": "教学楼电梯口，敞开的轿厢连接不同楼层，门前的空地留下匆忙往返与相遇。",
  "group-restaurant": "杭州旅途中的团餐厅，圆桌转盘上摆着汤锅和碗筷，大家围坐着分享一天的见闻。",
  "teacher-office": "光线昏暗的教师办公室，卷起一半的遮光帘后透进天光，沙发长椅靠在堆满书本的办公桌旁。",
  "company-basement": "《镜中花》中的公司地下室。灯光照着狭长通道与拐角，储藏室里的账本静静等待来人。",
  "company-gate": "《镜中花》中的建材公司门外。紧闭的大门隔开厂区和门前空地，远处是厂房与工业设施。",
  "classroom-night": "夜间的七班教室。窗外已经暗下，室内的灯还亮着，桌面上的功课陪伴晚自习。",
  "classroom-snow": "雪天的七班教室。窗外树枝和屋顶覆着积雪，柔和的冬日天光落在熟悉的课桌上。",
  "classroom-exam": "布置成考场的教室，课桌拉开距离，桌面与桌斗清空，墙上的钟继续走着。",
  "classroom-window": "从七班教室窗边望出去，窗台、树梢和楼下校园连成另一幅课间风景。",
  "sports-dome": "气膜馆内，弧形膜顶罩住整片运动场地，篮架与球场线在柔和的光线下展开。",
  "backstage": "舞台侧翼的后台，幕布、服装架和长凳挤出一块准备空间，上台前的忙乱暂时停在这里。",
  "songcheng-stage": "宋城剧场的舞台，传统建筑布景铺开，绿色光束穿过薄雾，观众席等待开场。",
  "songcheng-rings": "宋城水面上的铁环设施，连续悬挂的圆环连接两端平台，水中映着树影与屋檐。",
  "cafeteria-entrance": "学校食堂门外，玻璃门映着校园树木。台阶前的一块空地，让来往的人停下来交谈。",
  "graduation-photo": "毕业合影前的校园场地。前排椅子与后方站台已经排好，空位等待熟悉的同学和老师。",
  "chronicle-desk": "摊在木课桌上的班史，方格纸、笔和一叠书沐浴在窗光里，还有新的故事可以写下。"
};
export const newBackgroundIds = ["listening-lab","washroom","elevator-lobby","group-restaurant","teacher-office","company-basement","company-gate","classroom-night","classroom-snow","classroom-exam","classroom-window","sports-dome","backstage","songcheng-stage","songcheng-rings","cafeteria-entrance","graduation-photo","chronicle-desk"];
export const backgroundFile=(id:string)=>(id==='sunset'?'classroom':id)+'.webp';
