import {BackgroundGallery} from './BackgroundGallery.tsx';
import {seenBackgrounds,mergeBackgrounds} from './backgroundUnlocks.ts';
import {backgroundFile} from './backgrounds.ts';
import React,{useEffect,useRef,useState,useMemo} from 'react';
import {createRoot} from 'react-dom/client';
import {byId, characters, countdown, enter, initial, story, dates, dateByDate, backgrounds, countdownLabel, weekday, skippedDates, failureCount, type Option} from './story';
import {newSave, parseSave, readLocal, applyCheat, unlockedDateIds, type Save} from './save';
import {portraitFor,filmPrototypeFor} from './portraits.ts';
import {ClassGallery} from './ClassGallery.tsx';
import {orderedOptions,textCharacters,readingSettings} from './reading.ts';
import {GameAudio,music,musicTrackFor,shouldPlayPage} from './audio.ts';
import './style.css';
const asset=(name:string)=>import.meta.env.BASE_URL+'assets/'+name;
const QA=import.meta.env.DEV&&new URLSearchParams(location.search).get('qa')==='1';
const namespace=QA?'seven.qa.':'seven.';
const AUTO=namespace+'autosave.v1',MANUAL=namespace+'manual.v1',RECORD=namespace+'records.v1',SETTINGS=namespace+'settings.v1';
function savedSettings(){try{return readingSettings(JSON.parse(localStorage.getItem(SETTINGS)||'{}'));}catch{return readingSettings({});}}
function records(){try{const v=JSON.parse(localStorage.getItem(RECORD)||'{}');const read:string[]=Array.isArray(v.read)?v.read.filter((id:unknown)=>typeof id==='string'&&byId[id]):[];return {read,failures:Array.isArray(v.failures)?v.failures.filter((x:unknown)=>typeof x==='string'):[],seenBackgrounds:seenBackgrounds({read,seenBackgrounds:Array.isArray(v.seenBackgrounds)?v.seenBackgrounds.filter((id:unknown)=>typeof id==='string'):undefined})};}catch{return {read:[],failures:[],seenBackgrounds:[]};}}
function App(){
 const [classPage,setClassPage]=useState(()=>location.hash==='#class');
 const [save,setSave]=useState<Save>(()=>{const s=readLocal(AUTO)||newSave();const r=records();return {...s,seenBackgrounds:mergeBackgrounds(seenBackgrounds(s),r.seenBackgrounds),read:[...new Set([...s.read,...r.read])],failures:[...new Set([...s.failures,...r.failures])]};});
 const [started,setStarted]=useState(false),[modal,setModal]=useState(''),[failure,setFailure]=useState(''),[auto,setAuto]=useState(false),[skip,setSkip]=useState(false),[count,setCount]=useState(0),[mobileSchedule,setMobileSchedule]=useState(false),[notice,setNotice]=useState('');
 const [cheatAnswer,setCheatAnswer]=useState(''),[cheatError,setCheatError]=useState(''),[cheatDone,setCheatDone]=useState(false);
 const [cheatBusy,setCheatBusy]=useState(false);
 const [musicBlocked,setMusicBlocked]=useState(false);const musicPlayer=useRef<GameAudio|null>(null);
 const [settings,setSettings]=useState(savedSettings);const [exportText,setExportText]=useState(''),[importText,setImportText]=useState(''); const audio=useRef<AudioContext|null>(null);const importRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{const change=()=>{setClassPage(location.hash==='#class');setAuto(false);setSkip(false);};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
 const frame=save.frame,n=byId[frame.node],pov=characters[frame.pov],actor=characters[frame.character],day=dateByDate[frame.date];
 useEffect(()=>{const player=new GameAudio(import.meta.env.BASE_URL+'audio/',setMusicBlocked);musicPlayer.current=player;const unlock=()=>player.unlock();const visible=()=>player.suspend(document.hidden);document.addEventListener('pointerdown',unlock);document.addEventListener('keydown',unlock);document.addEventListener('visibilitychange',visible);return()=>{player.dispose();musicPlayer.current=null;document.removeEventListener('pointerdown',unlock);document.removeEventListener('keydown',unlock);document.removeEventListener('visibilitychange',visible);};},[]);
 useEffect(()=>{musicPlayer.current?.setVolumes(settings.musicVolume,settings.volume);},[settings.musicVolume,settings.volume]);
 const currentMusic=started&&!classPage?musicTrackFor(frame):music.roles.theme;
 useEffect(()=>{musicPlayer.current?.setTrack(currentMusic);},[currentMusic]);
 useEffect(()=>{if(!started||classPage)return;setSave(s=>{const seen=seenBackgrounds(s);return seen.includes(s.frame.background)?s:{...s,seenBackgrounds:mergeBackgrounds(seen,[s.frame.background])};});},[started,classPage,frame.background]);
 const prototype=filmPrototypeFor(frame.character,frame.date);
 const unlocked=new Set([...(QA?dates.map(d=>d.id):[]),...unlockedDateIds(save)]);
 const isSpecial=n.kind==='date'||n.kind==='portrait'||n.kind==='scene';
 const letters=useMemo(()=>textCharacters(n.text),[n.text]);
 const options=useMemo(()=>orderedOptions(n.id,n.options),[n.id,n.options]);
 const complete=count>=letters.length;
 useEffect(()=>{if(!started)return;try{localStorage.setItem(AUTO,JSON.stringify(save));localStorage.setItem(RECORD,JSON.stringify({read:save.read,failures:save.failures,seenBackgrounds:seenBackgrounds(save)}));}catch{setNotice('浏览器无法写入存档，请使用导出备份。');}},[save,started]);
 useEffect(()=>{try{localStorage.setItem(SETTINGS,JSON.stringify(settings));}catch{/* in-memory settings remain usable */}},[settings]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(t);},[notice]);
 useEffect(()=>{setCount(0);},[n.id,started]);
 useEffect(()=>{if(!started)return;if(isSpecial||settings.instantText){setCount(letters.length);return;}const t=setInterval(()=>setCount(c=>{if(c>=letters.length){clearInterval(t);return c;}return c+1;}),settings.speed);return()=>clearInterval(t);},[n.id,started,settings.speed,settings.instantText,isSpecial,letters]);
 function sound(){if(settings.uiVolume===0)return;try{const a=audio.current??new AudioContext();audio.current=a;void a.resume();const osc=a.createOscillator(),gain=a.createGain();osc.type='sine';osc.frequency.setValueAtTime(430,a.currentTime);osc.frequency.exponentialRampToValueAtTime(220,a.currentTime+0.06);gain.gain.setValueAtTime(settings.uiVolume*0.07,a.currentTime);gain.gain.exponentialRampToValueAtTime(0.0001,a.currentTime+0.09);osc.connect(gain);gain.connect(a.destination);osc.start();osc.stop(a.currentTime+0.1);}catch{/* sound is optional */}}
 function go(id:string){const target=enter(save.frame,id);if(shouldPlayPage(save.frame,target,byId[id].kind))musicPlayer.current?.flipPage();setSave(s=>({...s,frame:enter(s.frame,id),read:[...new Set([...s.read,n.id])],history:n.kind==='line'||n.kind==='end'?[...s.history,{node:n.id,speaker:n.speaker||'旁白',text:n.text,date:s.frame.date,context:s.frame.context}].slice(-6000):s.history}));sound();}
 function advance(){if(!started||classPage||modal||failure)return;if(!complete){setCount(letters.length);return;}if(n.kind==='choice'||n.kind==='end')return;if(n.next)go(n.next);}
 function choose(o:Option){sound();if(o.failure){setFailure(o.failure);setAuto(false);setSkip(false);setSave(s=>({...s,read:[...new Set([...s.read,n.id])],failures:[...new Set([...s.failures,o.failure!])]}));}else if(o.next)go(o.next);}
 useEffect(()=>{if(!started||classPage||!auto||modal||failure||n.kind==='choice'||n.kind==='end'||!complete)return;const t=setTimeout(advance,isSpecial?2600:Math.max(1800,n.text.length*65));return()=>clearTimeout(t);},[started,classPage,auto,modal,failure,n.id,complete]);
 useEffect(()=>{if(!skip||!started||classPage||modal||failure)return;if(n.kind==='choice'||n.kind==='end'||!save.read.includes(n.id)){setSkip(false);return;}const t=setTimeout(()=>n.next&&go(n.next),150);return()=>clearTimeout(t);},[skip,started,classPage,modal,failure,n.id,save.read]);
 function retry(){setFailure('');setCount(letters.length);}
 useEffect(()=>{function key(e:KeyboardEvent){
  const target=e.target as HTMLElement;
  if(target.closest('input,select,textarea,[contenteditable="true"]'))return;
  if(e.repeat)return;
  if(failure&&!modal&&!classPage&&(e.code==='Space'||e.key==='Enter')){e.preventDefault();retry();return;}
  if(classPage){if(e.key==='Escape')location.hash='';return;}
  if(e.key==='Escape'){setModal('');setMobileSchedule(false);return;}
  if(/^[1-9]$/.test(e.key)&&n.kind==='choice'&&!failure&&!modal&&started){const o=options[Number(e.key)-1];if(o){e.preventDefault();choose(o);}return;}
  if(target.closest('button'))return;
  if(e.code==='Space'||e.key==='Enter'){e.preventDefault();advance();}
 }window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
 function mergeLoad(s:Save){const r=records();setSave({...s,seenBackgrounds:mergeBackgrounds(seenBackgrounds(save),seenBackgrounds(s),r.seenBackgrounds),read:[...new Set([...save.read,...s.read,...r.read])],failures:[...new Set([...save.failures,...s.failures,...r.failures])]});setFailure('');setAuto(false);setSkip(false);setModal('');setStarted(true);setNotice('已恢复进度');}
 function exportSave(){const text=JSON.stringify(save,null,2);setExportText(text);const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='七班日志-存档.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);setNotice('已生成存档；也可复制下方文本备份。');}
 async function importSave(file?:File){if(!file)return;try{mergeLoad(parseSave(await file.text()));}catch(e){setNotice(e instanceof Error?e.message:'导入失败');}if(importRef.current)importRef.current.value='';}
 async function confirmCheat(e:React.FormEvent){
  e.preventDefault();if(cheatBusy)return;setCheatBusy(true);
  let unlockedSave:Save|null;
  try{unlockedSave=await applyCheat(save,cheatAnswer);}catch{setCheatError('当前环境无法校验，请通过 HTTPS 或 localhost 打开游戏。');return;}finally{setCheatBusy(false);}
  if(!unlockedSave){setCheatError('还差一点火候。请逐字填对，再试一次。');return;}
  setSave(unlockedSave);setCheatError('');setCheatDone(true);setAuto(false);setSkip(false);sound();
  try{localStorage.setItem(AUTO,JSON.stringify(unlockedSave));localStorage.setItem(RECORD,JSON.stringify({read:unlockedSave.read,failures:unlockedSave.failures,seenBackgrounds:seenBackgrounds(unlockedSave)}));}catch{setNotice('本次已解锁，但无法保存，请开始游戏后导出存档备份。');}
 }
 function startNew(){setSave({...newSave(),read:save.read,failures:save.failures,seenBackgrounds:seenBackgrounds(save)});setFailure('');setAuto(false);setSkip(false);setStarted(true);setModal('');musicPlayer.current?.flipPage();sound();}
 useEffect(()=>{setMobileSchedule(false);},[frame.date]);
 const schedule=<><div className="tape"/><span className="small-label">CLASS / 07</span><h2>{day.schedule?'今日课表':'今日行程'}</h2><p className="schedule-date">{frame.date.slice(5).replace('-',' / ')} · {['星期日','星期一','星期二','星期三','星期四','星期五','星期六'][new Date(frame.date+'T00:00:00Z').getUTCDay()]}</p>{!day.schedule&&<p className="no-course">原页未载课表 · 剧情行程</p>}<div className="schedule-list">{(day.schedule||day.itinerary).map((x,i)=><div key={i} className={'schedule-row '+(!day.schedule&&frame.period===x?'active':'')}><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b>{!day.schedule&&frame.period===x&&<i>◀</i>}</div>)}</div><div className="paper-bottom">{day.schedule?day.scheduleNote:'先把今天留下来。'}</div></>;
 if(modal==='backgrounds')return <BackgroundGallery unlocked={seenBackgrounds(save)} onClose={()=>setModal('menu')}/>;
 if(classPage)return <ClassGallery date={frame.date} onClose={()=>{location.hash='';}}/>;
 return <div className={'app '+(settings.reduced?'reduce-motion':'')+' effect-'+(started?n.effect||'normal':'normal')+' '+(frame.context?.includes('戏中戏')?'film-mode':frame.context?.includes('回忆')?'memory-mode':'')}>
 <div className={'scene scene-'+frame.background} style={{backgroundImage:`url(${asset(backgroundFile(frame.background))})`}}/><div className="scene-shade"/>
 {!started&&<button className="cover-sound" onPointerDown={e=>e.stopPropagation()} onKeyDown={e=>e.stopPropagation()} onClick={()=>{if(musicBlocked){if(settings.musicVolume===0)setSettings({...settings,musicVolume:.35});musicPlayer.current?.unlock();}else setSettings({...settings,musicVolume:settings.musicVolume>0?0:.35});}}>{musicBlocked?'♫ 开启音乐':settings.musicVolume>0?'♫ 音乐 ON':'♫ 音乐 OFF'}</button>}{QA&&<span className="qa-badge">验收模式 · 独立存档</span>}{!started?<main className="title-screen"><div className="edition">人大附中 2024 届 · 高三（7）班</div><div className="title-paper"><span className="title-number">07</span><div><p>我们的故事，自己来写。</p><h1>七班<span>日志</span></h1><p className="english">THE DAYS WE WROTE</p></div></div><div className="chapter-title"><span>第{["", "一", "二", "三", "四", "五", "六"][day.chapter]}章 / {frame.date.replaceAll("-", ".")}</span><h2>{day.title}</h2></div><div className="start-actions"><button className="primary start-action" disabled={!readLocal(AUTO)} onClick={()=>{setStarted(true);sound();}}>继续上次的记录 <span>→</span></button><button className="primary start-action" onClick={startNew}>翻开第一页 <span>↗</span></button><button className="primary start-action" onClick={()=>{setCheatAnswer('');setCheatError('');setCheatDone(false);setModal('cheat');}}>全解锁作弊码 <span>↗</span></button><a className="primary start-action" href="#class">全班人物 <span>↗</span></a><button className="text-button" onClick={()=>setModal('about')}>关于七班日志</button></div><p className="title-footer">校园视觉小说 · 全篇 {dates.length} 日 <span>空格 / 点击推进 · 数字键选择</span></p></main>:<>
 <header className="topbar"><div className="date-badge"><button className="date-schedule-trigger" aria-label={mobileSchedule?'收起课表行程':'查看课表行程'} aria-expanded={mobileSchedule} aria-controls="daily-schedule" onClick={()=>setMobileSchedule(!mobileSchedule)}/><span>{frame.date.slice(0,4)} · {weekday(frame.date)}</span><strong>{Number(frame.date.slice(5,7))}<em>/</em>{Number(frame.date.slice(8))}</strong><small className="date-schedule-hint">{mobileSchedule?'收起':day.schedule?'查看课表':'查看行程'} <span aria-hidden="true">{mobileSchedule?'▴':'▾'}</span></small></div><div className="countdown">{countdown(frame.date)>0?<><span>距高考</span><b>{countdown(frame.date)}</b><span>天</span></>:<strong>{countdownLabel(frame.date)}</strong>}</div><div className="scene-location"><span>CHAPTER {String(day.chapter).padStart(2,'0')}</span><strong>{backgrounds[frame.background]}</strong><small>{frame.period}</small></div><button className="menu-trigger" onClick={()=>setModal('menu')} aria-label="打开菜单">☰ <span>手帐</span></button></header>
 {mobileSchedule&&<button className="schedule-dismiss" aria-label="关闭课表行程" onClick={()=>setMobileSchedule(false)}/>}<aside id="daily-schedule" aria-label="课表行程" className={'schedule '+(mobileSchedule?'mobile-open':'')}><button className="schedule-close" aria-label="收起课表行程" onClick={()=>setMobileSchedule(false)}>×</button>{schedule}</aside>
 <section className="scene-info" aria-label="当前剧情"><div className="scene-heading">{frame.context&&frame.context.trim()!=='现实'&&<div className="context-tag">{frame.context}</div>}<div className="chapter-tag"><span>第{day.chapter}章 · {day.chapterTitle}</span><b>{day.title}</b></div></div>{frame.prop&&<aside className={'foreground prop-'+frame.prop.kind} key={frame.period}><span>{frame.prop.title}</span>{frame.prop.lines.map(line=><b key={line}>{line}</b>)}</aside>}</section>
 {actor&&<div className={'portrait-stage'+(prototype?' has-prototype':'')} key={frame.character}><div className="portrait-halo"/>{prototype&&<img className="portrait-echo" src={asset(prototype.image)} alt={actor.name+'借名对应的'+prototype.name+'映像'}/>}<img className="portrait" src={asset(portraitFor(frame.character,frame.date))} alt={actor.name+'的二次元立绘'}/><span className="portrait-name">{actor.actor?actor.actor+' 饰 '+actor.name:actor.name}</span></div>}
 <div className="pov"><span>当前视角</span><strong>{pov.name}</strong><i>↗</i></div>
 <main className={'dialogue-wrap '+(n.kind==='choice'?'has-choice':'')}>
 {n.kind==='choice'&&<div className="choices" aria-label="对白选择">{options.map((o,i)=><button key={o.text} onClick={()=>choose(o)}><span>0{i+1}</span>{o.text}<i>↗</i></button>)}</div>}
 <button className="dialogue" onClick={advance} aria-label="推进对白" disabled={n.kind==='choice'||n.kind==='end'}><div className="speaker"><span>{n.speaker||'七班日志'}</span><small>{/心声|内心/.test(n.speaker||'')?'INNER VOICE':n.speaker==='动作'?'ACTION':n.speaker==='旁白'?'NARRATION':'DIALOGUE'}</small></div><p className="typewriter" aria-label={n.text}><span className="typewriter-space" aria-hidden="true">{n.text}</span><span className="typewriter-ink" aria-hidden="true">{letters.slice(0,count).join('')}{!complete&&<span className="cursor">▍</span>}</span></p><div className="dialogue-meta"><span>LOG {String(story.indexOf(n)+1).padStart(2,'0')} / {String(story.length).padStart(2,'0')}</span><span>{n.kind==='choice'?'选择你的回应':n.kind==='end'?'七班日志 · 全篇完':'点击 / SPACE 继续'} <b>◆</b></span></div></button>
 {n.kind==='end'&&<div className="end-actions"><button onClick={startNew}>从开场重读 ↺</button><button onClick={()=>setModal('credits')}>毕业留念 ↗</button><button onClick={()=>setModal('collection')}>失败结语 · {save.failures.length}/{failureCount}</button></div>}
 <nav className="toolbar" aria-label="游戏控制"><button onClick={()=>setModal('history')}>回看</button><button className={auto?'selected':''} onClick={()=>{setAuto(!auto);setSkip(false);}}>自动 {auto?'ON':'OFF'}</button><button className={skip?'selected':''} onClick={()=>{setSkip(!skip);setAuto(false);}}>已读快进</button><button onClick={()=>setModal('save')}>存档</button><button onClick={()=>setModal('collection')}>结语 <b>{save.failures.length}/{failureCount}</b></button><button onClick={()=>setModal('settings')}>设置</button></nav>
 </main>
 {isSpecial&&<div className={'transition '+(n.kind==='date'?'calendar-transition':n.kind==='scene'?'scene-transition':'character-transition')} key={n.id}><div className="transition-grid"/>{n.kind==='date'?<><span className="transition-kicker">{n.id==='calendar'?'把我们的日子，写成一本书。':'把今天留在上一页。'}</span><p className="calendar-year">{frame.date.slice(0,4)} / 高三</p><div className="calendar-big"><span>{Number(frame.date.slice(5,7))}</span><i>/</i><strong>{Number(frame.date.slice(8))}</strong></div><h2>{day.title}</h2><p className="calendar-count">{countdownLabel(frame.date)}</p>{frame.context?.includes("待核")&&<p className="calendar-count">日历暂排 · 事件实际日期待核</p>}<div className="calendar-strips" aria-hidden="true">{skippedDates(frame.date).map((date,i)=><span key={date} style={{animationDelay:(i*.055)+'s'}}>{date}</span>)}</div></>:n.kind==='scene'?<div className="scene-card">{frame.context&&frame.context.trim()!=='现实'&&<span>{frame.context}</span>}<h2>{n.text}</h2><p>{backgrounds[frame.background]}</p></div>:<><img src={asset(portraitFor(frame.pov,frame.date))} alt={pov.name}/><div className="entrance-copy"><span>视角切换 / NOW YOU ARE</span><h2>{pov.name}</h2><p>{pov.role}</p><b>{n.text}</b></div></>}<button className="transition-continue" onClick={()=>{if(n.next)go(n.next);}}>{n.kind==='scene'?'继续这一段':'进入这一页'} <span>→</span></button></div>}
 </>}
 {failure&&<div className="failure-overlay" role="dialog" aria-modal="true" aria-label="一句话失败"><div className="crossout">这一笔，写岔了。</div><span className="small-label">A NOTE IN THE MARGIN</span><p>{failure}</p><button className="primary" onClick={()=>{retry();sound();}}>重新选择 ↺</button><small>已收入失败结语 · SPACE / 点击重选</small></div>}
 {modal&&<div className="modal-shade" onClick={()=>setModal('')}><section className={'modal modal-'+modal} role="dialog" aria-modal="true" aria-label={modal==='cheat'?'全解锁作弊码':modal} onClick={e=>e.stopPropagation()}><button className="close" aria-label="关闭" onClick={()=>setModal('')}>×</button><span className="small-label">CLASS SEVEN / NOTEBOOK</span><h2>{{menu:'我的手帐',history:'对白回看',save:'保存这一页',collection:'写岔的那些笔',settings:'阅读设置',about:'关于七班日志',timeline:'日期与章节',people:'出场人物',credits:'七班之魂永在',cheat:'全解锁作弊码'}[modal]}</h2>
 {modal==='cheat'&&<>{cheatDone?<div className="cheat-success"><p role="status">全部内容已解锁。</p><p>所有日期、全部对白的已读快进、失败结语与毕业留念，都可以随时翻看。当前剧情位置保持不变，解锁记录随存档保存。</p><div className="menu-grid"><button onClick={()=>setModal('timeline')}>选择日期 ↗</button><button onClick={()=>setModal('')}>返回封面 ↗</button></div></div>:<form className="cheat-form" onSubmit={confirmCheat}><p className="cheat-question">朱考儒说我写得不对，_____。</p><label htmlFor="cheat-answer">填入空白处<input id="cheat-answer" autoFocus autoComplete="off" spellCheck={false} value={cheatAnswer} onChange={e=>{setCheatAnswer(e.target.value);setCheatError('');}} aria-describedby="cheat-error"/></label><p id="cheat-error" className="cheat-error" role="alert">{cheatError}</p><button className="primary" type="submit" disabled={cheatBusy} aria-busy={cheatBusy}>{cheatBusy?'校验中…':'验证并全解锁'} <span>↗</span></button></form>}</>}
 {modal==='menu'&&<div className="menu-grid">{[['history','对白回看'],['save','存档与读档'],['collection','失败结语'],['backgrounds','背景图鉴'],['settings','阅读设置'],['timeline','日期与章节'],['people','出场人物'],['about','全篇与出处']].map(([id,label])=><button key={id} onClick={()=>setModal(id)}>{label} ↗</button>)}<a className="gallery-menu-link" href="#class" onClick={()=>setModal('')}>全班人物 ↗</a>{save.read.some(id=>byId[id]?.kind==='end')&&<button onClick={()=>setModal('credits')}>毕业留念 ↗</button>}<button onClick={()=>{setStarted(false);setModal('');setAuto(false);setSkip(false);}}>返回封面</button></div>}
 {modal==='history'&&<div className="history-list">{save.history.length?save.history.map((h,i)=><article key={i}><small>{h.date}{h.context&&h.context.trim()!=='现实'?' · '+h.context:''} · {h.speaker}</small><p>{h.text}</p></article>):<p>还没有翻过的对白。第一页就在眼前。</p>}</div>}
 {modal==='collection'&&<><p className="muted">共收集 {save.failures.length} / {failureCount} 句。重选和读档都会保留。</p>{save.failures.map(x=><article className="failure-note" key={x}>{x}</article>)}{Array.from({length:Math.max(0,failureCount-save.failures.length)},(_,i)=><article className="locked" key={i}>尚未写岔的那一笔 · ？</article>)}</>}
 {modal==='save'&&<><p>当前位置：{frame.date} · {pov.name} · 第 {story.indexOf(n)+1} 段</p><div className="menu-grid"><button onClick={()=>{try{localStorage.setItem(MANUAL,JSON.stringify(save));setNotice('手动存档已保存');}catch{setNotice('保存失败，请导出存档');}}}>保存到手动档</button><button disabled={!readLocal(MANUAL)} onClick={()=>{const s=readLocal(MANUAL);if(s)mergeLoad(s);}}>读取手动档</button><button onClick={exportSave}>导出 JSON 存档</button><button onClick={()=>importRef.current?.click()}>导入存档</button></div><p className="muted">每次推进自动保存。版本 2（兼容样章版本 1）· 存档只保存在当前浏览器；换设备请导出。</p><details><summary>粘贴存档文本恢复</summary><textarea aria-label="粘贴存档文本" value={importText} onChange={e=>setImportText(e.target.value)} style={{width:"100%",height:120,fontSize:12}}/><button disabled={!importText.trim()} onClick={()=>{try{mergeLoad(parseSave(importText));setImportText('');}catch(e){setNotice(e instanceof Error?e.message:'导入失败');}}}>恢复文本存档</button></details>{exportText&&<details open><summary>存档文本备份</summary><p className="muted">下载受浏览器限制时，可复制文本保存为 .json 文件，再通过导入存档恢复。</p><textarea aria-label="导出的存档文本" readOnly value={exportText} style={{width:"100%",height:160,fontSize:12}}/></details>}</>}
 {modal==='settings'&&<><label>背景音乐 · {music.tracks[currentMusic].title} <span>{Math.round(settings.musicVolume*100)}%</span><input aria-label="背景音乐音量" type="range" min="0" max="1" step="0.05" value={settings.musicVolume} onChange={e=>setSettings({...settings,musicVolume:Number(e.target.value)})}/></label>{musicBlocked&&<button className="primary" onClick={()=>musicPlayer.current?.unlock()}>开启音乐 ↗</button>}<label>操作音效 <span>{Math.round(settings.uiVolume*100)}%</span><input aria-label="操作音效音量" type="range" min="0" max="1" step="0.05" value={settings.uiVolume} onChange={e=>setSettings({...settings,uiVolume:Number(e.target.value)})}/></label><label>文字速度 <span>{settings.speed} ms / 字</span><input type="range" min="10" max="100" value={settings.speed} onChange={e=>setSettings({...settings,speed:Number(e.target.value)})}/></label><label>翻页音效 <span>{Math.round(settings.volume*100)}%</span><input type="range" min="0" max="1" step="0.05" value={settings.volume} onChange={e=>setSettings({...settings,volume:Number(e.target.value)})}/></label><label className="check"><input type="checkbox" checked={settings.reduced} onChange={e=>setSettings({...settings,reduced:e.target.checked})}/>减少过场动画</label><label className="check"><input type="checkbox" checked={settings.instantText} onChange={e=>setSettings({...settings,instantText:e.target.checked})}/>即时显示全文（关闭逐字效果）</label><p className="muted">点击对白或空格推进，数字键选择；失败页按空格重选，Esc 关闭手帐。自动播放遇到选择会等待；快进仅跳过已读段落。每天翻日期播放真实纸页声，读档不补播；音乐在同一场景连续播放，无角色配音。</p></>}
 {modal==='timeline'&&<><p className="muted">{dates.length}个保留日期；读过的日期可重访，收集记录不会丢失。</p><div className="timeline-list">{dates.map(d=><button key={d.id} disabled={!unlocked.has(d.id)} onClick={()=>{if(frame.date!==d.date)musicPlayer.current?.flipPage();setFailure('');setAuto(false);setSkip(false);setSave(old=>({...old,frame:enter(initial,d.entry)}));setStarted(true);setModal('');}}><span>{d.date}</span><b>{d.title}</b><small>{unlocked.has(d.id)?'已解锁':'待翻到'}</small></button>)}</div></>}
 {modal==='credits'&&<><img className="graduation-page" src={asset('source-255.webp')} alt="班史第255页作者、毕业留念与结语"/><p>七班日志：全体同学与韩琪老师。第二、三部：李沛霖、彭逸涵、凌艺坤、徐启元、吕思宇、贾盛元、张瑞麒。</p></>}
 {modal==='people'&&<div className="people-list">{Object.entries(characters).map(([id,c])=><article key={id}><img src={asset(portraitFor(id,frame.date))} alt={c.name+'的立绘'}/><div><h3>{c.name}</h3><p>{c.role}</p>{c.bio&&<p>{c.bio}</p>}{c.actor&&<small>演员：{c.actor}，剧情行为只属虚构角色。</small>}</div></article>)}</div>}
 {modal==='about'&&<><p><a href={import.meta.env.BASE_URL+'audio/credits.txt'} target="_blank" rel="noopener noreferrer">音乐与翻页声署名、来源及授权 ↗</a></p><p>从2023年7月16日的《入境 · 入静 · 劲》开始，经{dates.length}个保留日期走到毕业。日常、人物往事与同学作品穿插，三幕《镜中花》按收录原稿展开。</p><p>已制作同学使用独立人物立绘：秋季学期为长袖，春季学期和暑假开场为短袖，服装随当前章节日期。电影角色使用对应演员的形象；尚无个人立绘的角色沿用原共用图片。每人保留独立ID，原图仍保留在资源目录。背景为美术化意象，非实景复原。</p><p>当前段落出处：PDF第{n.pages?.join('、')||String(n.page).padStart(3,'0')}页 · {n.source}。页码、补写与原文信息随节点保存。现实日期在顶栏，回忆及戏中戏时间在场景标签。高考后改用毕业季文案。</p><p className="muted">杭州分日、电影缺场景十一及机票／月份异文保留在来源说明中。已确认人物以用户确认优先；成功选择汇合原载事件，失败为原创一句并直接重选。</p><a href={asset('source-008.webp')} target="_blank" rel="noreferrer">查看首日班史原页 ↗</a></>}
 </section></div>}
 <input hidden type="file" accept="application/json,.json" ref={importRef} onChange={e=>void importSave(e.target.files?.[0])}/>
 {notice&&<div className="toast" role="status">{notice}</div>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
