// Generated by scripts/produce-content.mjs; stable day and node IDs.
const data = {
  "xu": {
    "name": "徐启元",
    "role": "物理课代表 · 班史与电影编写者",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "开篇写《入境·入静·劲》与序，参与电影编剧和导演。"
  },
  "lei": {
    "name": "雷昱",
    "role": "数学课代表 · 电影音乐",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "接任数学课代表，喜欢音乐，参与电影配乐。"
  },
  "ling": {
    "name": "凌艺坤",
    "role": "记录者 · 电影导演之一",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "在周一接笔；班史里有朱考儒的谐音称呼，参与《镜中花》导演。"
  },
  "c03": {
    "name": "徐子涵",
    "role": "满者 · 三者之一",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "“又满不了了”得名；答疑、录音、礼仪奖与爱金子的玩笑都留在班史。"
  },
  "c04": {
    "name": "雷雨泽",
    "role": "雷导 · 历史答疑同行",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "在《数论》中陪满者答疑，并在出门后解读可乐；与生物老师雷杨不同。"
  },
  "c05": {
    "name": "李沛霖",
    "role": "班史编写者 · 电影编剧与导演",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "参与发电站、电影筹备和编写，是硝矢公；不等于彭逸涵。"
  },
  "c06": {
    "name": "吕思宇",
    "role": "雪茗 · 班史编写者",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "参与班史写作与《汝坟》《溱洧》的唱响诗经活动。"
  },
  "c07": {
    "name": "刘恒怿",
    "role": "大哥 · Izzy",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "因喜欢数字七选择七班；数学竞速、听口练习和小马卡片在班史中交替出现。"
  },
  "c08": {
    "name": "陈俊言",
    "role": "七班同学",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c09": {
    "name": "周远持",
    "role": "七班同学",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c10": {
    "name": "黄鹤鸣",
    "role": "新同学 · 黄院士",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "新学期加入，课间随机出现，“太幽默了昂”是常见口癖。"
  },
  "c11": {
    "name": "陈熙",
    "role": "七班同学",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c12": {
    "name": "彭逸涵",
    "role": "硝彭 · 班史编写者",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "写下高三是长跑，参与旅行与电影，饰演金跃山。"
  },
  "c13": {
    "name": "戚洪硕",
    "role": "七班同学",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c14": {
    "name": "惠子宁",
    "role": "《邵聪观察日志》记录者",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "留意邵聪的一天，互相逗趣，也认真帮助他讲题；关系按用户确认保留暧昧。"
  },
  "c15": {
    "name": "刘树苡",
    "role": "四大之一 · 电影剪辑",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "画抽象作品、谈材料题，拒演警探而做电影剪辑。"
  },
  "c16": {
    "name": "戴向阳",
    "role": "四大之一 · 唐诗作者",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "写唐诗、整理知识、探索规则边界，课堂插话有自己的语气。"
  },
  "c17": {
    "name": "李沐衡",
    "role": "电教与数码 · 小帮凶",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "帮课堂设备、默写素材和居家架机，也用词典笔播放音乐。"
  },
  "c18": {
    "name": "焉家祎",
    "role": "七班同学",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c19": {
    "name": "马诗雨",
    "role": "七班同学",
    "image": "girl.png",
    "color": "#ffbe52",
    "gender": "女",
    "bio": ""
  },
  "c20": {
    "name": "刘美孜",
    "role": "七班同学",
    "image": "girl.png",
    "color": "#ffbe52",
    "gender": "女",
    "bio": ""
  },
  "c21": {
    "name": "李玉",
    "role": "七班同学",
    "image": "girl.png",
    "color": "#ffbe52",
    "gender": "女",
    "bio": ""
  },
  "c22": {
    "name": "李昊宇",
    "role": "七班同学",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c23": {
    "name": "秦敏然",
    "role": "分班后的故人 · 电影演员",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "有打印退款与失职道歉的往事，后来参与电影，饰演秦旻然。"
  },
  "c24": {
    "name": "张鹤闻",
    "role": "小我 · 乐队与电影演员",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "想买卷帘钢琴，在电影中饰演代向阳；不是戴向阳本人。"
  },
  "c25": {
    "name": "王家童",
    "role": "萌童 · 雷学与竞速",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "制作雷学封面，参与数学竞速，保有扫雷高级纪录。"
  },
  "c26": {
    "name": "贾盛元",
    "role": "七班同学",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c27": {
    "name": "张沐雷",
    "role": "七班同学",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c28": {
    "name": "贾诺基",
    "role": "七班同学",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c29": {
    "name": "张瑞麒",
    "role": "七班同学",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c30": {
    "name": "邵聪",
    "role": "观察日志里的同桌",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "起初不许记录，讲对题时又要求记上，晚上反过来夸惠子宁聪明。"
  },
  "c31": {
    "name": "唐朝",
    "role": "七班同学",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c32": {
    "name": "童莘淇",
    "role": "七班同学",
    "image": "girl.png",
    "color": "#ffbe52",
    "gender": "女",
    "bio": ""
  },
  "c33": {
    "name": "冯子豪",
    "role": "七班同学",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c34": {
    "name": "李承容",
    "role": "七班同学",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c35": {
    "name": "史绍恺",
    "role": "七班同学",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c36": {
    "name": "石杨",
    "role": "七班同学",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c37": {
    "name": "黄艺博",
    "role": "四大之一 · 电影演员",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "自述由同学评议，不能把全部吹嘘当史实；在电影中饰演黄义薄。"
  },
  "c38": {
    "name": "郑泽一",
    "role": "郑导 · 七班同学",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "也称郑导、Roy Zheng，参与满者称号、杭州画伞和套圈故事。"
  },
  "c39": {
    "name": "张怀锦",
    "role": "七班同学",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c40": {
    "name": "杨京赫",
    "role": "七班同学",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c41": {
    "name": "孙佳怡",
    "role": "七班同学",
    "image": "girl.png",
    "color": "#ffbe52",
    "gender": "女",
    "bio": ""
  },
  "c42": {
    "name": "赵梓伊",
    "role": "七班同学",
    "image": "girl.png",
    "color": "#ffbe52",
    "gender": "女",
    "bio": ""
  },
  "c43": {
    "name": "程洛怡",
    "role": "温辞 · 七班同学",
    "image": "girl.png",
    "color": "#ffbe52",
    "gender": "女",
    "bio": "曾以温辞署名，参与记录七班日常。"
  },
  "c44": {
    "name": "戴杨洁",
    "role": "七班同学",
    "image": "girl.png",
    "color": "#ffbe52",
    "gender": "女",
    "bio": ""
  },
  "c45": {
    "name": "韩琪",
    "role": "HQ · 班主任与物理老师",
    "image": "girl.png",
    "color": "#ffbe52",
    "gender": "女",
    "bio": "筛题、讲义、答疑与成绩分析；也与全班一起写日志。"
  },
  "c46": {
    "name": "孙蕾",
    "role": "语文老师",
    "image": "girl.png",
    "color": "#ffbe52",
    "gender": "女",
    "bio": "资料、批改、读书与课本剧，在学生回忆中有认真也有玩笑。"
  },
  "c47": {
    "name": "杨卫华",
    "role": "杨sir · 英语老师",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "条理鲜明，愿听同学辩论；声音趣事与冯子豪相像。"
  },
  "c48": {
    "name": "战景林",
    "role": "能者 · 数学老师",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "强调基础、自主学习与慢就是快，也参与课堂竞速。"
  },
  "c49": {
    "name": "雷杨",
    "role": "出场老师",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c50": {
    "name": "朱泽萱",
    "role": "智者 · 政治老师",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "智者村、金斧、朱礼属于课堂与班级创作。"
  },
  "c51": {
    "name": "朱老师",
    "role": "历史老师 · 数论答疑",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": "历史办公室中的朱老师，全名未扩写，与政治老师朱泽萱使用不同角色ID。"
  },
  "c52": {
    "name": "张强",
    "role": "出场老师",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c53": {
    "name": "博老师",
    "role": "出场老师",
    "image": "girl.png",
    "color": "#ffbe52",
    "gender": "女",
    "bio": ""
  },
  "c54": {
    "name": "蒋老师",
    "role": "出场老师",
    "image": "girl.png",
    "color": "#ffbe52",
    "gender": "女",
    "bio": ""
  },
  "c55": {
    "name": "臧春梅",
    "role": "出场老师",
    "image": "girl.png",
    "color": "#ffbe52",
    "gender": "女",
    "bio": ""
  },
  "c56": {
    "name": "崔鹏",
    "role": "出场老师",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c57": {
    "name": "李岩",
    "role": "出场老师",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c58": {
    "name": "亓孝然",
    "role": "出场老师",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "c60": {
    "name": "徐子瀚",
    "role": "七班同学",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "bio": ""
  },
  "film-秦旻然": {
    "name": "秦旻然",
    "role": "《镜中花》虚构角色 · 秦敏然饰",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "actor": "秦敏然",
    "bio": "虚构角色，演员为秦敏然，依第242页演职表。"
  },
  "film-秦嘉然": {
    "name": "秦嘉然",
    "role": "《镜中花》虚构角色 · 童莘淇饰",
    "image": "girl.png",
    "color": "#ffbe52",
    "gender": "女",
    "actor": "童莘淇",
    "bio": "虚构角色，演员为童莘淇，依第242页演职表。"
  },
  "film-刘树颐": {
    "name": "刘树颐",
    "role": "《镜中花》虚构角色 · 周远持饰",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "actor": "周远持",
    "bio": "虚构角色，演员为周远持，依第242页演职表。"
  },
  "film-代向阳": {
    "name": "代向阳",
    "role": "《镜中花》虚构角色 · 张鹤闻饰",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "actor": "张鹤闻",
    "bio": "虚构角色，演员为张鹤闻，依第242页演职表。"
  },
  "film-黄义薄": {
    "name": "黄义薄",
    "role": "《镜中花》虚构角色 · 黄艺博饰",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "actor": "黄艺博",
    "bio": "虚构角色，演员为黄艺博，依第242页演职表。"
  },
  "film-金跃山": {
    "name": "金跃山",
    "role": "《镜中花》虚构角色 · 彭逸涵饰",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "actor": "彭逸涵",
    "bio": "虚构角色，演员为彭逸涵，依第242页演职表。"
  },
  "film-石邵楷": {
    "name": "石邵楷",
    "role": "《镜中花》虚构角色 · 贾盛元饰",
    "image": "xu.png",
    "color": "#a18aff",
    "gender": "男",
    "actor": "贾盛元",
    "bio": "虚构角色，演员为贾盛元，依第242页演职表。"
  },
  "film-李程蓉": {
    "name": "李程蓉",
    "role": "《镜中花》虚构角色 · 李玉饰",
    "image": "girl.png",
    "color": "#ffbe52",
    "gender": "女",
    "actor": "李玉",
    "bio": "虚构角色，演员为李玉，依第242页演职表。"
  }
};
export default data;
