// Generated by scripts/produce-content.mjs; stable day and node IDs.
const data = [
  {
    "id": "D01",
    "date": "2023-07-16",
    "basis": "中／原载；已实现",
    "title": "入境 · 入静 · 劲",
    "pov": "徐启元",
    "pages": "008",
    "assets": "B01、B02；黄昏滤色、纸页UI复用",
    "sourcePages": [
      8
    ],
    "chapter": 1,
    "chapterTitle": "入境与相遇",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "calendar",
    "itinerary": [
      "集结",
      "迁楼",
      "入境",
      "往事",
      "班会",
      "新任",
      "落笔",
      "当日收尾"
    ]
  },
  {
    "id": "D02",
    "date": "2023-07-17",
    "basis": "中／原载；扩写预览",
    "title": "高三的第一个周一",
    "pov": "凌艺坤",
    "pages": "009、181",
    "assets": "B01、B02、B03；O01、O03",
    "sourcePages": [
      9,
      181
    ],
    "chapter": 1,
    "chapterTitle": "入境与相遇",
    "schedule": [
      "英",
      "英",
      "语",
      "数",
      "数",
      "英语答疑",
      "化",
      "C",
      "物",
      "物"
    ],
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "next-date",
    "itinerary": [
      "课堂",
      "称呼的旧事",
      "午间"
    ]
  },
  {
    "id": "D03",
    "date": "2023-07-20",
    "basis": "中／原载",
    "title": "课堂里的例题",
    "pov": "吕思宇→刘恒怿（数学课段）",
    "pages": "012",
    "assets": "B01、B03；O02",
    "sourcePages": [
      12
    ],
    "chapter": 1,
    "chapterTitle": "入境与相遇",
    "schedule": [
      "语",
      "语",
      "英",
      "数",
      "数",
      "物",
      "化",
      "C",
      "C"
    ],
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D03-date",
    "itinerary": [
      "课堂"
    ]
  },
  {
    "id": "D04",
    "date": "2023-07-22",
    "basis": "长／原载年份按上下文校正为2023",
    "title": "不说再见",
    "pov": "程洛怡（温辞）",
    "pages": "014",
    "assets": "B01、B02、B15；O02、O03",
    "sourcePages": [
      14
    ],
    "chapter": 1,
    "chapterTitle": "入境与相遇",
    "schedule": [
      "语",
      "英",
      "数",
      "化",
      "物",
      "C",
      "家长会"
    ],
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D04-date",
    "itinerary": [
      "微写作"
    ]
  },
  {
    "id": "D05",
    "date": "2023-08-23",
    "basis": "短／原载",
    "title": "摸底讲评",
    "pov": "凌艺坤",
    "pages": "016",
    "assets": "B01、B02；小白条仅作不辨内容的道具",
    "sourcePages": [
      16
    ],
    "chapter": 1,
    "chapterTitle": "入境与相遇",
    "schedule": [
      "语",
      "语",
      "英",
      "数",
      "数",
      "C",
      "化",
      "物",
      "物"
    ],
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D05-date",
    "itinerary": [
      "摸底讲评"
    ]
  },
  {
    "id": "D06",
    "date": "2023-08-25",
    "basis": "中／原载",
    "title": "窗边",
    "pov": "戴向阳→徐子涵（旁观回忆）",
    "pages": "018、182",
    "assets": "B01、B03、B04；O04",
    "sourcePages": [
      18,
      182
    ],
    "chapter": 1,
    "chapterTitle": "入境与相遇",
    "schedule": [
      "C",
      "C",
      "化",
      "物",
      "物",
      "语",
      "英",
      "数",
      "数"
    ],
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D06-date",
    "itinerary": [
      "窗边",
      "小公主六一",
      "慢与快"
    ]
  },
  {
    "id": "D07",
    "date": "2023-08-30",
    "basis": "中／原载",
    "title": "军训仍在继续",
    "pov": "陈俊言→周远持",
    "pages": "020",
    "assets": "B01、B03、B04",
    "sourcePages": [
      20
    ],
    "chapter": 1,
    "chapterTitle": "入境与相遇",
    "schedule": [
      "化",
      "C",
      "物",
      "英",
      "英",
      "语",
      "数",
      "数",
      "班会"
    ],
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D07-date",
    "itinerary": [
      "军训仍在继续",
      "班会",
      "百分之九十"
    ]
  },
  {
    "id": "D08",
    "date": "2023-09-01",
    "basis": "中／原载",
    "title": "新学期",
    "pov": "黄鹤鸣→陈熙",
    "pages": "022、212开头",
    "assets": "B01、B02、B04；O01",
    "sourcePages": [
      22,
      212
    ],
    "chapter": 2,
    "chapterTitle": "秋日与同路人",
    "schedule": [
      "英",
      "语",
      "数",
      "物",
      "化",
      "C"
    ],
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D08-date",
    "itinerary": [
      "新学期",
      "新同学问进度",
      "七对等位基因"
    ]
  },
  {
    "id": "D09",
    "date": "2023-09-02",
    "basis": "长／原载与列传明确日期互证",
    "title": "第一次周六补课",
    "pov": "彭逸涵→徐子涵",
    "pages": "023—024、186—187",
    "assets": "B01、B02、B09；O05",
    "sourcePages": [
      23,
      24,
      186,
      187
    ],
    "chapter": 2,
    "chapterTitle": "秋日与同路人",
    "schedule": [
      "语",
      "英",
      "数",
      "化",
      "物",
      "C"
    ],
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D09-date",
    "itinerary": [
      "第一次周六补课",
      "金子啊金子",
      "次日再问",
      "称号的来处",
      "夜里补一笔"
    ]
  },
  {
    "id": "D10",
    "date": "2023-09-09",
    "basis": "长／原载；09-10是续文落款",
    "title": "教师节前",
    "pov": "戚公子→吕思宇→李沐衡",
    "pages": "033—035、184—185",
    "assets": "B01、B03、B04、B10；O06、I04",
    "sourcePages": [
      33,
      34,
      35,
      184,
      185
    ],
    "chapter": 2,
    "chapterTitle": "秋日与同路人",
    "schedule": [
      "化",
      "物",
      "C",
      "语",
      "英",
      "数"
    ],
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D10-date",
    "itinerary": [
      "教师节前",
      "智者村",
      "八比一",
      "礼与歌",
      "公开课白板",
      "回到今天"
    ]
  },
  {
    "id": "D11",
    "date": "2023-09-13",
    "basis": "中／原载",
    "title": "纸飞机与照片",
    "pov": "惠子宁",
    "pages": "038—040",
    "assets": "B01、B03、B04；O03",
    "sourcePages": [
      38,
      39,
      40
    ],
    "chapter": 2,
    "chapterTitle": "秋日与同路人",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D11-date",
    "itinerary": [
      "纸飞机与照片",
      "被瓜分的午休"
    ]
  },
  {
    "id": "D12",
    "date": "2023-09-19",
    "basis": "长／原载",
    "title": "去食堂的路上",
    "pov": "李沛霖→刘树苡",
    "pages": "046—047、194、198—200",
    "assets": "B01、B03、B05；O07",
    "sourcePages": [
      46,
      47,
      194,
      198,
      199,
      200
    ],
    "chapter": 2,
    "chapterTitle": "秋日与同路人",
    "schedule": [
      "语",
      "语",
      "英",
      "英",
      "数（加速）",
      "化",
      "物",
      "历史"
    ],
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D12-date",
    "itinerary": [
      "去食堂的路上",
      "差一点",
      "艺术现场",
      "飞机兑奖",
      "铁柜与背包雁",
      "作文的比喻",
      "记睡时"
    ]
  },
  {
    "id": "D13",
    "date": "2023-09-21",
    "basis": "长／原载",
    "title": "当开新页",
    "pov": "戴向阳",
    "pages": "050、194—195、201、226",
    "assets": "B01、B03、B10、B17；O03、O07",
    "sourcePages": [
      50,
      194,
      195,
      201,
      226
    ],
    "chapter": 2,
    "chapterTitle": "秋日与同路人",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D13-date",
    "itinerary": [
      "当开新页",
      "巨佬的初识",
      "园博园",
      "发电站",
      "诗的旁批",
      "坝",
      "戴语传开",
      "石钟山记课间"
    ]
  },
  {
    "id": "D14",
    "date": "2023-09-25",
    "basis": "长／原载",
    "title": "设备有事",
    "pov": "李沐衡",
    "pages": "054、200；185仅回扣不重播",
    "assets": "B01、B02、B03、B04；O06",
    "sourcePages": [
      54,
      200,
      185
    ],
    "chapter": 2,
    "chapterTitle": "秋日与同路人",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D14-date",
    "itinerary": [
      "设备有事",
      "高二的接口",
      "小帮凶",
      "回到课间"
    ]
  },
  {
    "id": "D15",
    "date": "2023-09-26",
    "basis": "中／原载",
    "title": "数卷子",
    "pov": "孙佳怡→焉家祎（数卷子段）",
    "pages": "055—056、182",
    "assets": "B01、B03、B06；O06",
    "sourcePages": [
      55,
      56,
      182
    ],
    "chapter": 2,
    "chapterTitle": "秋日与同路人",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D15-date",
    "itinerary": [
      "数卷子",
      "午睡之后"
    ]
  },
  {
    "id": "D16",
    "date": "2023-09-28",
    "basis": "中／原载",
    "title": "牌位",
    "pov": "马诗雨→徐子涵",
    "pages": "059—060、186—187",
    "assets": "B01、B03；O08",
    "sourcePages": [
      59,
      60,
      186,
      187
    ],
    "chapter": 2,
    "chapterTitle": "秋日与同路人",
    "schedule": [
      "化",
      "C",
      "物",
      "语",
      "英",
      "体",
      "数",
      "数"
    ],
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D16-date",
    "itinerary": [
      "牌位",
      "文明礼仪奖",
      "节前"
    ]
  },
  {
    "id": "D17",
    "date": "2023-10-08",
    "basis": "长／原载",
    "title": "七点半出发",
    "pov": "刘美孜→刘恒怿（合照段）",
    "pages": "061—062",
    "assets": "B11、B12、B15；O09",
    "sourcePages": [
      61,
      62
    ],
    "chapter": 2,
    "chapterTitle": "秋日与同路人",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D17-date",
    "itinerary": [
      "七点半出发",
      "九点半到达",
      "登顶",
      "返校"
    ]
  },
  {
    "id": "D18",
    "date": "2023-10-09",
    "basis": "特长／当天原载，杭州为插叙",
    "title": "改错之后，重游杭州",
    "pov": "李玉→徐启元→彭逸涵→石杨子然",
    "pages": "063—064、186、198—199、209、217—219",
    "assets": "B01、B21—B25；I01—I03、O03、O10、O16",
    "sourcePages": [
      63,
      64,
      186,
      198,
      199,
      209,
      217,
      218,
      219
    ],
    "chapter": 2,
    "chapterTitle": "秋日与同路人",
    "schedule": [
      "数",
      "英",
      "化",
      "物",
      "C",
      "语",
      "体",
      "班"
    ],
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D18-date",
    "itinerary": [
      "改错后翻出游学照片",
      "出发与良渚",
      "良渚的惆怅",
      "一盒纸的去向",
      "沙发边的纸团",
      "谁在洗牌",
      "西湖的同名文章",
      "满江红与声光电",
      "铁环与奶茶",
      "千年的绿色激光",
      "分茶",
      "一圈伞面",
      "鸡从碗里出来",
      "再赴西湖",
      "西溪上空",
      "崔老师走到牌桌前",
      "吹哨与邀牌",
      "照片合上"
    ]
  },
  {
    "id": "D19",
    "date": "2023-10-11",
    "basis": "长／原载",
    "title": "操场香蕉",
    "pov": "李昊宇→秦敏然",
    "pages": "066—069、211、220",
    "assets": "B01、B02、B03、B04；O03、O11",
    "sourcePages": [
      66,
      67,
      68,
      69,
      211,
      220
    ],
    "chapter": 2,
    "chapterTitle": "秋日与同路人",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D19-date",
    "itinerary": [
      "操场香蕉",
      "大家原来很信任他",
      "失职故人",
      "打印费差了数毛",
      "分班后的故人",
      "回到操场"
    ]
  },
  {
    "id": "D20",
    "date": "2023-10-12",
    "basis": "中／原载",
    "title": "我爱学习",
    "pov": "吕思宇→张鹤闻（乐器段）",
    "pages": "070—073、207、209",
    "assets": "B01、B02、B03；I06、O01、O03、O12",
    "sourcePages": [
      70,
      71,
      72,
      73,
      207,
      209
    ],
    "chapter": 2,
    "chapterTitle": "秋日与同路人",
    "schedule": [
      "化",
      "C",
      "物",
      "语",
      "英",
      "体",
      "数",
      "自习",
      "数限"
    ],
    "scheduleNote": "英与自习有对调箭头",
    "entry": "D20-date",
    "itinerary": [
      "我爱学习",
      "老师读书",
      "时间错开",
      "批红"
    ]
  },
  {
    "id": "D21",
    "date": "2023-10-20",
    "basis": "长／原载",
    "title": "五册雷学",
    "pov": "凌艺坤→王家童（萌童，用户确认）",
    "pages": "082—083",
    "assets": "B01、B02、B06；O13",
    "sourcePages": [
      82,
      83
    ],
    "chapter": 2,
    "chapterTitle": "秋日与同路人",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D21-date",
    "itinerary": [
      "五册雷学",
      "门外展览",
      "办公室对视"
    ]
  },
  {
    "id": "D22",
    "date": "2023-10-24",
    "basis": "中／原载",
    "title": "数学册被发现",
    "pov": "徐子涵→凌艺坤",
    "pages": "088",
    "assets": "B01、B02、B03；O14",
    "sourcePages": [
      88
    ],
    "chapter": 2,
    "chapterTitle": "秋日与同路人",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D22-date",
    "itinerary": [
      "数学册被发现",
      "实验后的地面"
    ]
  },
  {
    "id": "D23",
    "date": "2023-10-31",
    "basis": "中／原载",
    "title": "考前的提醒",
    "pov": "李沛霖（采用在场同学的改编视角）",
    "pages": "090—091",
    "assets": "B01、B02；O05",
    "sourcePages": [
      90,
      91
    ],
    "chapter": 2,
    "chapterTitle": "秋日与同路人",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D23-date",
    "itinerary": [
      "考前的提醒",
      "期中首日"
    ]
  },
  {
    "id": "D24",
    "date": "2023-11-06",
    "basis": "长／原载，黄艺博旧事为编排插叙",
    "title": "八件乐器",
    "pov": "张鹤闻→黄艺博→李沛霖",
    "pages": "093、196—198",
    "assets": "B01、B03、B10、B17；O03、O12",
    "sourcePages": [
      93,
      196,
      197,
      198
    ],
    "chapter": 3,
    "chapterTitle": "冬日课间",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D24-date",
    "itinerary": [
      "八件乐器",
      "植物园门前",
      "先问什么叫前女友",
      "好友验证界面",
      "与班里的人也有关系",
      "曹雪芹故居",
      "晚风与乒乓球",
      "泡面与付款",
      "李悦琳怎么来的",
      "数月之后的揭晓",
      "乐器还在桌上"
    ]
  },
  {
    "id": "D25",
    "date": "2023-11-14",
    "basis": "长／原载",
    "title": "早读迟到",
    "pov": "贾盛元→徐启元（阅读HQ记录的编排视角）",
    "pages": "097、100、181—182",
    "assets": "B01、B02、B05、B10；O15",
    "sourcePages": [
      97,
      100,
      181,
      182
    ],
    "chapter": 3,
    "chapterTitle": "冬日课间",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D25-date",
    "itinerary": [
      "早读迟到",
      "老师的一天",
      "将军的来处",
      "另一页工作记录",
      "收好纸页",
      "群里怎么没人回"
    ]
  },
  {
    "id": "D26",
    "date": "2023-11-16",
    "basis": "长／原载；聚餐由204/206互证",
    "title": "二十多人的一碗面",
    "pov": "贾诺基→李沛霖→张沐雷（聚餐段）",
    "pages": "102—103、204、206",
    "assets": "B01、B02、B13；O16",
    "sourcePages": [
      102,
      103,
      204,
      206
    ],
    "chapter": 3,
    "chapterTitle": "冬日课间",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D26-date",
    "itinerary": [
      "自习变数学",
      "面店",
      "赶回",
      "朋友圈"
    ]
  },
  {
    "id": "D27",
    "date": "2023-11-17",
    "basis": "长／当天原载，称号形成是旧事",
    "title": "一碗面打赌",
    "pov": "贾诺基→张瑞麒",
    "pages": "104、188—189",
    "assets": "B01；O05、O06、O16",
    "sourcePages": [
      104,
      188,
      189
    ],
    "chapter": 3,
    "chapterTitle": "冬日课间",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D27-date",
    "itinerary": [
      "一碗面打赌",
      "飞出来的因式",
      "贴吧在课前打开",
      "十分钟与两天",
      "右手二十分钟",
      "今天下课"
    ]
  },
  {
    "id": "D28",
    "date": "2023-11-22",
    "basis": "长／原载，食堂其他逸事为插叙",
    "title": "考完，到火炉火",
    "pov": "刘美孜→徐子涵→惠子宁",
    "pages": "107、187、189、204—206；011午饭回忆",
    "assets": "B01、B05、B13、B32；O16",
    "sourcePages": [
      107,
      187,
      189,
      204,
      205,
      206,
      11
    ],
    "chapter": 3,
    "chapterTitle": "冬日课间",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D28-date",
    "itinerary": [
      "考完，到火炉火",
      "后来推荐自助餐",
      "新的队伍",
      "李先生"
    ]
  },
  {
    "id": "D29",
    "date": "2023-11-27",
    "basis": "长／原载，黄鹤鸣列传为回顾插入",
    "title": "院士刷新",
    "pov": "戚公子→黄鹤鸣",
    "pages": "109、212",
    "assets": "B01、B02、B03；O17",
    "sourcePages": [
      109,
      212
    ],
    "chapter": 3,
    "chapterTitle": "冬日课间",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D29-date",
    "itinerary": [
      "院士刷新",
      "我来帮你",
      "回到午休",
      "院士的手先到了",
      "得意门生"
    ]
  },
  {
    "id": "D30",
    "date": "2023-11-29",
    "basis": "短／原载",
    "title": "听口将近",
    "pov": "刘恒怿",
    "pages": "111",
    "assets": "B01；O05",
    "sourcePages": [
      111
    ],
    "chapter": 3,
    "chapterTitle": "冬日课间",
    "schedule": [
      "物",
      "C",
      "化",
      "数",
      "数",
      "午休",
      "英",
      "语",
      "自习",
      "语限"
    ],
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D30-date",
    "itinerary": [
      "听口将近",
      "数学竞速前声",
      "夜自习"
    ]
  },
  {
    "id": "D31",
    "date": "2023-12-01",
    "basis": "长／原载",
    "title": "教室安静之后",
    "pov": "徐子涵→李沛霖",
    "pages": "112",
    "assets": "B01、B02、B07",
    "sourcePages": [
      112
    ],
    "chapter": 3,
    "chapterTitle": "冬日课间",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D31-date",
    "itinerary": [
      "教室安静之后",
      "办公室门前"
    ]
  },
  {
    "id": "D32",
    "date": "2023-12-06",
    "basis": "长／原载",
    "title": "生日",
    "pov": "刘恒怿",
    "pages": "114、213—214前段",
    "assets": "B01、B03、B09；O01、O18",
    "sourcePages": [
      114,
      213,
      214
    ],
    "chapter": 3,
    "chapterTitle": "冬日课间",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D32-date",
    "itinerary": [
      "生日",
      "为什么七班",
      "睡觉奖",
      "生日与小马",
      "生日的最后一笔"
    ]
  },
  {
    "id": "D33",
    "date": "2023-12-13",
    "basis": "长／13—15网课原载；雪晨为前几日回忆",
    "title": "雪天回到教室",
    "pov": "刘树苡→刘恒怿→吕思宇",
    "pages": "115、181、186、213—214、235—239",
    "assets": "B01、B10、B04雪景、B09；I04、O18、O19",
    "sourcePages": [
      115,
      181,
      186,
      213,
      214,
      235,
      236,
      237,
      238,
      239
    ],
    "chapter": 3,
    "chapterTitle": "冬日课间",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D33-date",
    "itinerary": [
      "雪天回到教室",
      "后门的目光",
      "事后自述",
      "做完还要题",
      "回到雪天这一页",
      "两次录音",
      "雪地的字",
      "书中的书"
    ]
  },
  {
    "id": "D34",
    "date": "2023-12-22",
    "basis": "中／原载",
    "title": "Material",
    "pov": "刘恒怿→刘树苡（争论段）",
    "pages": "116",
    "assets": "B01、B03",
    "sourcePages": [
      116
    ],
    "chapter": 3,
    "chapterTitle": "冬日课间",
    "schedule": [
      "英",
      "数",
      "数",
      "语",
      "语",
      "午休",
      "C",
      "化",
      "物",
      "生限"
    ],
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D34-date",
    "itinerary": [
      "Material",
      "物理改错"
    ]
  },
  {
    "id": "D35",
    "date": "2023-12-26",
    "basis": "长／原载",
    "title": "公车上书",
    "pov": "凌艺坤→陈俊言",
    "pages": "117",
    "assets": "B01、B02、B07暂定；O05。办公室科属待核",
    "sourcePages": [
      117
    ],
    "chapter": 3,
    "chapterTitle": "冬日课间",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D35-date",
    "itinerary": [
      "先问九班的分数",
      "等在生物办公室"
    ]
  },
  {
    "id": "D36",
    "date": "2023-12-27",
    "basis": "特长／原载日期有覆盖；12-28小注分层",
    "title": "邵聪观察日志",
    "pov": "邵聪→惠子宁（日志作者，用户确认）",
    "pages": "118—121、209",
    "assets": "B01、B03、B05；O20。28日补记单列卡片",
    "sourcePages": [
      118,
      119,
      120,
      121,
      209
    ],
    "chapter": 3,
    "chapterTitle": "冬日课间",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D36-date",
    "itinerary": [
      "自己选成同桌",
      "同桌身边的起哄",
      "观察对象就在旁边",
      "收藏幸福的交付之路",
      "第二节数学",
      "我的汤，大杂烩",
      "孙老师还是不在",
      "越翻越多",
      "自习的十二分钟",
      "他又夸我聪明",
      "各自的同好"
    ]
  },
  {
    "id": "D37",
    "date": "2024-01-04",
    "basis": "长／日记原载；信件时间有冲突",
    "title": "六圈",
    "pov": "马诗雨→戴向阳",
    "pages": "128—130、195",
    "assets": "B01、B03、B04；O21",
    "sourcePages": [
      128,
      129,
      130,
      195
    ],
    "chapter": 3,
    "chapterTitle": "冬日课间",
    "schedule": [
      "化",
      "生（C）",
      "物",
      "语",
      "英",
      "体",
      "数",
      "自"
    ],
    "scheduleNote": "原页生物括注C，其余C为选科",
    "entry": "D37-date",
    "itinerary": [
      "六圈",
      "给自己的信",
      "手工作坊",
      "重新启动",
      "纯色衣服"
    ]
  },
  {
    "id": "D38",
    "date": "2024-01-05",
    "basis": "长／原载",
    "title": "病后返课",
    "pov": "童莘淇→徐子涵→彭逸涵",
    "pages": "131—132、185、199、240—241",
    "assets": "B01、B10；B01舞台版、O04、O22",
    "sourcePages": [
      131,
      132,
      185,
      199,
      240,
      241
    ],
    "chapter": 3,
    "chapterTitle": "冬日课间",
    "schedule": [
      "英",
      "数",
      "数",
      "语",
      "语",
      "生",
      "化",
      "物"
    ],
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D38-date",
    "itinerary": [
      "病后返课",
      "邓肯王上台",
      "裤子先裂了",
      "诗经里的声音",
      "回到今天",
      "小马卡片",
      "明天又高考"
    ]
  },
  {
    "id": "D39",
    "date": "2024-01-09",
    "basis": "短／原载",
    "title": "听口查分",
    "pov": "雷昱（编排观察视角，不据此认定“雷皇”署名）",
    "pages": "135—136",
    "assets": "B01、B03；O23",
    "sourcePages": [
      135,
      136
    ],
    "chapter": 3,
    "chapterTitle": "冬日课间",
    "schedule": [
      "英",
      "英",
      "数",
      "语",
      "语",
      "物",
      "化",
      "C"
    ],
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D39-date",
    "itinerary": [
      "听口查分",
      "AI的旧窗口",
      "长夜中途"
    ]
  },
  {
    "id": "D39A",
    "date": "2024-01-11",
    "basis": "中／原载；本轮新增",
    "title": "望梅止渴 · 梅利屋",
    "pov": "唐朝→徐子涵",
    "pages": "138、205—206",
    "assets": "B01、B03；O16",
    "sourcePages": [
      138,
      205,
      206
    ],
    "chapter": 3,
    "chapterTitle": "冬日课间",
    "schedule": [
      "化",
      "C",
      "物",
      "英",
      "语",
      "体",
      "数",
      "班"
    ],
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D39A-date",
    "itinerary": [
      "体育与纪律",
      "菜单"
    ]
  },
  {
    "id": "D40",
    "date": "2024-01-12",
    "basis": "中／原载",
    "title": "两篇作文",
    "pov": "周远持→雷昱",
    "pages": "139",
    "assets": "B01、B03；O12",
    "sourcePages": [
      139
    ],
    "chapter": 3,
    "chapterTitle": "冬日课间",
    "schedule": [
      "英",
      "数",
      "数",
      "语",
      "语",
      "C",
      "化",
      "物"
    ],
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D40-date",
    "itinerary": [
      "两篇作文",
      "和弦",
      "皆不可扣"
    ]
  },
  {
    "id": "D41",
    "date": "2024-01-26",
    "basis": "特长／改班牌有明确日期",
    "title": "绳球与钉",
    "pov": "陈熙→戚公子→李沛霖→戚公子",
    "pages": "122、124—127、143—146、203、214",
    "assets": "B01、B02、B16；O17、O24",
    "sourcePages": [
      122,
      124,
      125,
      126,
      127,
      143,
      144,
      145,
      146,
      203,
      214
    ],
    "chapter": 3,
    "chapterTitle": "冬日课间",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D41-date",
    "itinerary": [
      "绳球与钉",
      "鸡在表达什么",
      "七德",
      "舞与帮助",
      "我来帮你",
      "汉语编程",
      "期末之后",
      "改班牌",
      "揭牌"
    ]
  },
  {
    "id": "D42",
    "date": "2024-01-29",
    "basis": "中／原载",
    "title": "换课",
    "pov": "陈俊言→冯子豪（拟定课堂视角）",
    "pages": "147、208",
    "assets": "B01、B02；O06",
    "sourcePages": [
      147,
      208
    ],
    "chapter": 3,
    "chapterTitle": "冬日课间",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D42-date",
    "itinerary": [
      "换课",
      "声音三段",
      "今天的麦"
    ]
  },
  {
    "id": "D43",
    "date": "2024-02-01",
    "basis": "短／原载",
    "title": "牛鼻凹",
    "pov": "邵聪（取当日“聪”段为入口）",
    "pages": "150",
    "assets": "B01、B02",
    "sourcePages": [
      150
    ],
    "chapter": 4,
    "chapterTitle": "百日与复习",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D43-date",
    "itinerary": [
      "牛鼻凹",
      "家教还是麦当劳",
      "肉松与蛋糕"
    ]
  },
  {
    "id": "D44",
    "date": "2024-02-27",
    "basis": "长／事件日由前言明确",
    "title": "劝学",
    "pov": "戚公子→徐子涵（短反应）",
    "pages": "152、155—156、229—231",
    "assets": "B01、B02、B07；O05",
    "sourcePages": [
      152,
      155,
      156,
      229,
      230,
      231
    ],
    "chapter": 4,
    "chapterTitle": "百日与复习",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D44-date",
    "itinerary": [
      "两零点的旧争论",
      "走向数学办公室",
      "十七点零八",
      "十七点十二",
      "十七点十八",
      "十七点二十八"
    ]
  },
  {
    "id": "D45",
    "date": "2024-02-28",
    "basis": "长／日常原载；游记为记录日上的插叙",
    "title": "尼德兰游记",
    "pov": "李沛霖→邵聪（课堂回忆）→戴向阳",
    "pages": "153、157—158、189—190、195、209",
    "assets": "B01、B19、B20-N；O25",
    "sourcePages": [
      153,
      157,
      158,
      189,
      190,
      195,
      209
    ],
    "chapter": 4,
    "chapterTitle": "百日与复习",
    "schedule": [
      "物",
      "C",
      "化",
      "数",
      "数",
      "英",
      "语",
      "班"
    ],
    "scheduleNote": "原页课序有涂改，C为选科",
    "entry": "D45-date",
    "itinerary": [
      "昨日承诺的后续",
      "四十六分",
      "尼德兰的开头",
      "街头",
      "咖啡馆",
      "回到课堂"
    ]
  },
  {
    "id": "D46",
    "date": "2024-02-29",
    "basis": "特长／誓师原载；《数论》自述“好像”该日",
    "title": "百日 · 数论",
    "pov": "李承容→徐子涵",
    "pages": "159—160、171—172、181",
    "assets": "B01、B02、B08；O26。誓师具体场地未证实，不新造礼堂",
    "sourcePages": [
      159,
      160,
      171,
      172,
      181
    ],
    "chapter": 4,
    "chapterTitle": "百日与复习",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D46-date",
    "itinerary": [
      "百日誓师",
      "以前也有刻名可乐",
      "她说天资愚钝",
      "三个人，一瓶老师的可乐",
      "卷子还没看，先问数学",
      "出门后的解读"
    ]
  },
  {
    "id": "D47",
    "date": "2024-03-01",
    "basis": "中／原载；可乐是承前推定翌日",
    "title": "可乐的次日",
    "pov": "雷雨泽→徐子涵",
    "pages": "161—162、172",
    "assets": "B01、B03；O26、O27",
    "sourcePages": [
      161,
      162,
      172
    ],
    "chapter": 4,
    "chapterTitle": "百日与复习",
    "schedule": [
      "英",
      "数",
      "数",
      "语",
      "语",
      "C",
      "化",
      "物",
      "地理限时"
    ],
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D47-date",
    "itinerary": [
      "次日的拉环",
      "心里跑两圈",
      "年夜饭的鱼",
      "明天到底有没有语文"
    ]
  },
  {
    "id": "D48",
    "date": "2024-03-06",
    "basis": "中／原载",
    "title": "听口之前的请假",
    "pov": "李沛霖→周远持",
    "pages": "163—164、181、183、187、214",
    "assets": "B01、B02、B14；O03、O19、O28",
    "sourcePages": [
      163,
      164,
      181,
      183,
      187,
      214
    ],
    "chapter": 4,
    "chapterTitle": "百日与复习",
    "schedule": [
      "物",
      "C",
      "化",
      "数",
      "数",
      "语",
      "英",
      "自习",
      "英限"
    ],
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D48-date",
    "itinerary": [
      "听口之前的请假",
      "隔间里两个人的声音",
      "展板"
    ]
  },
  {
    "id": "D49",
    "date": "2024-03-07",
    "basis": "中／原载",
    "title": "千米与一圈",
    "pov": "张鹤闻→徐子涵（往事）",
    "pages": "165—166、187",
    "assets": "B01、B04；O29",
    "sourcePages": [
      165,
      166,
      187
    ],
    "chapter": 4,
    "chapterTitle": "百日与复习",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D49-date",
    "itinerary": [
      "千米与一圈",
      "守门也要加圈"
    ]
  },
  {
    "id": "D50",
    "date": "2024-03-08",
    "basis": "中／原载",
    "title": "小卖部补货",
    "pov": "李沐衡→张沐雷",
    "pages": "167、200",
    "assets": "B01、B02、B03、B10；O06、O30、O35",
    "sourcePages": [
      167,
      200
    ],
    "chapter": 4,
    "chapterTitle": "百日与复习",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D50-date",
    "itinerary": [
      "小卖部补货",
      "修墙与架机",
      "AI进群",
      "手机的旧一局",
      "回到今天",
      "架起手机"
    ]
  },
  {
    "id": "D51",
    "date": "2024-03-14",
    "basis": "长／原载",
    "title": "解析竞速记",
    "pov": "刘恒怿→王家童",
    "pages": "169—170、188—190、193",
    "assets": "B01、B03；O05；萌童＝王家童已确认",
    "sourcePages": [
      169,
      170,
      188,
      189,
      190,
      193
    ],
    "chapter": 4,
    "chapterTitle": "百日与复习",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D51-date",
    "itinerary": [
      "班门口迎战",
      "先讲例七",
      "第一轮",
      "第二轮的密谋",
      "西瓜和西柚",
      "西翼的来处"
    ]
  },
  {
    "id": "D52",
    "date": "2024-04-02",
    "basis": "特长／日常原载，电影回忆为编排",
    "title": "镜中花 · 第一幕",
    "pov": "凌艺坤→李沛霖→秦敏然／秦旻然→童莘淇／秦嘉然",
    "pages": "174、211、220、242—245",
    "assets": "B01、B04、B10、B17、B20-H、B26、B29、B31；O22、O31",
    "sourcePages": [
      174,
      211,
      220,
      242,
      243,
      244,
      245
    ],
    "chapter": 5,
    "chapterTitle": "春日与镜中花",
    "schedule": [
      "英",
      "英",
      "数",
      "语",
      "语",
      "物",
      "化",
      "C"
    ],
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D52-date",
    "itinerary": [
      "春的标题",
      "邮箱里的期限",
      "数毛变成一个镇",
      "警探换演员",
      "第一幕 · 春光之后",
      "场景一：兄妹在走路",
      "场景二：火车驶向远方，夜色渐暗，传来爆炸和尖叫声。",
      "场景三：会议室里",
      "场景四：咖啡厅里",
      "场景五：运动场中",
      "场景六：办公室中，秦旻然正在翻着调查报告",
      "场景七：秦嘉然回家",
      "幕布之后"
    ]
  },
  {
    "id": "D53",
    "date": "2024-04-16",
    "basis": "特长／日常原载，电影回忆为编排",
    "title": "镜中花 · 第二幕",
    "pov": "徐启元→石杨子然→李沛霖→周远持／刘树颐→黄艺博／黄义薄→彭逸涵／金跃山",
    "pages": "175、198、221、245—252",
    "assets": "B01、B02、B05、B17、B18、B20-H、B26—B30、B33；O22、O31",
    "sourcePages": [
      175,
      198,
      221,
      245,
      246,
      247,
      248,
      249,
      250,
      251,
      252
    ],
    "chapter": 5,
    "chapterTitle": "春日与镜中花",
    "schedule": [
      "英",
      "英",
      "数",
      "语",
      "语",
      "物",
      "化",
      "C"
    ],
    "scheduleNote": "原页“同左”，沿用4月2日课表",
    "entry": "D53-date",
    "itinerary": [
      "三月二十九日约拍",
      "食堂门外",
      "回班路上",
      "后来得知缘由",
      "传闻与回班",
      "二钗的回信",
      "摇镜头",
      "两个机位互拍",
      "办公室没借成",
      "场景八：在房间中，刘树颐和秦旻然正在审问代向阳",
      "场景九：黄义薄的回忆",
      "场景十：回到现在",
      "场景十二：咖啡厅，秦嘉然、秦旻然和刘树颐在讨论",
      "场景十三：办公室",
      "场景十四：刘树颐去钢材公司调查",
      "场景十五：办公室里",
      "场景十六：街头",
      "场景十七：公园里，金跃山和秦嘉然在散步",
      "场景十八：七年前的回忆",
      "幕布之后"
    ]
  },
  {
    "id": "D54",
    "date": "2024-04-22",
    "basis": "长／原载；21日录音作为昨日",
    "title": "群里那段录音",
    "pov": "徐子涵→惠子宁",
    "pages": "176、187",
    "assets": "B01、B03；O03、O32",
    "sourcePages": [
      176,
      187
    ],
    "chapter": 5,
    "chapterTitle": "春日与镜中花",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D54-date",
    "itinerary": [
      "群里那段录音",
      "证书与合影",
      "一模分析"
    ]
  },
  {
    "id": "D55",
    "date": "2024-05-10",
    "basis": "特长／编排锚点，不宣称真实放映日",
    "title": "镜中花 · 第三幕",
    "pov": "张沐雷→李沛霖→秦敏然／秦旻然→周远持／刘树颐→凌艺坤",
    "pages": "220—221、252—254",
    "assets": "B01、B18、B20-H、B26、B27、B29、B33；O22、O31",
    "sourcePages": [
      220,
      221,
      252,
      253,
      254
    ],
    "chapter": 6,
    "chapterTitle": "毕业，再会",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D55-date",
    "itinerary": [
      "医务室的一张机票",
      "笑场空隙的采访",
      "秦敏然看成片",
      "场景十九：刘树颐发现秦旻然非法调转资金",
      "场景二十：秦嘉然向秦旻然哭诉",
      "场景二十一：石绍楷和秦旻然的谈话",
      "场景二十二：咖啡厅，刘树颐和秦旻然互相指认，真相大白",
      "场景二十三：医院中，秦旻然的回忆",
      "场景二十四：咖啡厅的最终谈话",
      "幕布之后"
    ]
  },
  {
    "id": "D56",
    "date": "2024-05-18",
    "basis": "长／推定锚点：177页倒计时20天，原日期涂改",
    "title": "二十天",
    "pov": "刘恒怿→戴向阳→彭逸涵（观察）",
    "pages": "177、181、196、214",
    "assets": "B01、B02、B03、B15；O16、O18、O33",
    "sourcePages": [
      177,
      181,
      196,
      214
    ],
    "chapter": 6,
    "chapterTitle": "毕业，再会",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D56-date",
    "itinerary": [
      "二十天",
      "找个安静地方",
      "柜门再打开",
      "扫雷纪录"
    ]
  },
  {
    "id": "D57",
    "date": "2024-05-31",
    "basis": "长／编排锚点，不认定重逢实日",
    "title": "毕业前的信",
    "pov": "吕思宇→程洛怡（温辞）",
    "pages": "209—210",
    "assets": "B01、B10、B15；O02、O03、O21",
    "sourcePages": [
      209,
      210
    ],
    "chapter": 6,
    "chapterTitle": "毕业，再会",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D57-date",
    "itinerary": [
      "毕业前的信",
      "名字代替合影",
      "留给以后的一页"
    ]
  },
  {
    "id": "D58",
    "date": "2024-06-07",
    "basis": "短／日历基准；过桥演出为原创",
    "title": "高考日",
    "pov": "徐启元",
    "pages": "008、024、177的回声；当天镜头为演出",
    "assets": "B01空景、B15；O21",
    "sourcePages": [
      8,
      24,
      177
    ],
    "chapter": 6,
    "chapterTitle": "毕业，再会",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D58-date",
    "itinerary": [
      "高考日"
    ]
  },
  {
    "id": "D59",
    "date": "2024-06-10",
    "basis": "中／编排锚点：按“高考历史毕”安排，非原文确日",
    "title": "七百分还是七百万",
    "pov": "徐子涵→雷雨泽→戴向阳",
    "pages": "187、196、201",
    "assets": "B15；O34",
    "sourcePages": [
      187,
      196,
      201
    ],
    "chapter": 6,
    "chapterTitle": "毕业，再会",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D59-date",
    "itinerary": [
      "七百分还是七百万",
      "为什么没出来",
      "考完的页边"
    ]
  },
  {
    "id": "D60",
    "date": "2024-06-11",
    "basis": "长／毕业框架编排；聚餐实日待确认",
    "title": "毕业，再会",
    "pov": "刘恒怿→黄鹤鸣→李沛霖→徐启元",
    "pages": "181、196、212、214、255",
    "assets": "B16、B01黄昏、B15；I05、O33",
    "sourcePages": [
      181,
      196,
      212,
      214,
      255
    ],
    "chapter": 6,
    "chapterTitle": "毕业，再会",
    "scheduleNote": "C表示选科课程，因人而异",
    "entry": "D60-date",
    "itinerary": [
      "毕业照的空椅",
      "凑凑宴请",
      "最后的数字",
      "三百一十四",
      "收齐书页"
    ]
  }
];
export default data;
