// Generated by scripts/produce-content.mjs; stable day and node IDs.
const data = [
  {
    "day": "D43",
    "text": "有人说报酬说好与发到手差得很远，原稿金额有歧义，不把传言改成确定工资。",
    "pages": [
      150
    ]
  }
];
export default data;
